/* Friend-only UI. Private data and empathy remain in the existing verified adapters. */
function V4FriendWorld({me,friend,state,myState,onOpen,panel}){
 const [quality,setQuality]=useState(V2_QUALITY),[records,setRecords]=useState([]),[socialReady,setSocialReady]=useState(false),[notice,setNotice]=useState(''),[sending,setSending]=useState(false),[justSent,setJustSent]=useState({});
 const alive=useRef(true),host=useRef(null),api=useRef(null),openRef=useRef(onOpen);openRef.current=onOpen;
 const [ui,setUI]=useState({x:-7,z:26}),[motion,setMotion]=useState(null),[menu,setMenu]=useState(false),[mapOpen,setMapOpen]=useState(false),[help,setHelp]=useState(false),[failed,setFailed]=useState(''),[lit,setLit]=useState(null),[reviewPose,setReviewPose]=useState(null),[welcome,setWelcome]=useState(true);
 useEffect(()=>{alive.current=true;SND.loop('bgm');return()=>{alive.current=false;SND.leave();};},[]);
 useEffect(()=>{try{
   const saved=reviewPose||V4_FRIEND_SESSIONS[friend.id]||{version:V2.version,x:-7,z:26,...V4_FRIEND_CAMERA};
   api.current=(V4_FRIEND_BEFORE?v2CreateWorld:v4CreateFriendWorld)(host.current,state,{open:a=>openRef.current(a),update:setUI,motion:setMotion},saved,{friend,islandId:friend.id,quality});
   return()=>{V4_FRIEND_SESSIONS[friend.id]=api.current.snapshot();api.current.dispose();};
 }catch(e){console.error('V4 visitor renderer:',e);setFailed('섬 화면을 열지 못했어요. 내 섬으로 돌아갔다가 다시 방문해 주세요.');}},[state,friend.id,quality,reviewPose]);
 useEffect(()=>{api.current?.pause(!!panel||help);},[panel,help,state,quality,reviewPose]);
 useEffect(()=>{let active=true;setSocialReady(false);empLoad(friend.id).then(list=>{if(active){setRecords(list);setSocialReady(true);}}).catch(()=>{if(active)setNotice('마음 연결을 불러오지 못했어요. 다시 방문해 주세요.');});return()=>{active=false;};},[friend.id]);
 useEffect(()=>{api.current?.setEmpathy(records);},[records,state,quality,reviewPose]);
 useEffect(()=>{api.current?.setDestination?.(lit);},[lit,quality,reviewPose]);
 async function send(){const p=ui.nearGrowth;if(!p||sending||!socialReady)return;setSending(true);setNotice('');try{const result=await v2SendEmpathy(me,friend,p.label);if(!alive.current)return;if(result.status==='sent-now'){setJustSent(m=>({...m,[dayStamp()+':'+p.label]:true}));setNotice('작은 반딧불에 마음을 담아 보냈어요.');api.current?.flyEmpathy(p,()=>{if(alive.current)setRecords(result.records);});}else setNotice(result.status==='sent'?'이 마음에는 오늘 이미 보냈어요.':result.status==='private'?'지금은 공개되지 않은 마음이에요.':'같은 쪽 마음을 기록해 본 뒤에 보낼 수 있어요.');}catch(e){if(alive.current)setNotice('보내지 못했어요. 잠시 후 다시 눌러 주세요.');}finally{if(alive.current)setSending(false);}}
 useEffect(()=>{if(!help&&!menu&&!mapOpen)return;const onKey=e=>{if(e.key==='Escape'){setHelp(false);setMenu(false);setMapOpen(false);}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[help,menu,mapOpen]);
 function guide(id){api.current?.setDestination?.(id);setLit(id);setMenu(false);setWelcome(false);setNotice(id==='growth'?'가까운 마음 식물이 빛나요. 직접 걸어가 살펴보세요.':id==='dock'?'돌아가는 부두가 빛나요.':'우리 반 게시판이 빛나요.');}
 function button(text,fn,cls='',label){return v4h('button',{type:'button',onClick:fn,className:cls,'aria-label':label||text},text);}
 const growth=ui.nearGrowth,rule=growth?(justSent[dayStamp()+':'+growth.label]?'sent':v2EmpathyRule(me,friend,state,myState,records,growth.label)):null;
 const destinationTitle=lit==='growth'?'마음 식물':lit==='dock'?'부두':lit==='board'?'우리 반 게시판':'';
 return v4h('main',{className:'v2-world v4-friend'+(motion?' v2-busy':'')},
  v4h('div',{className:'v2-canvas',ref:host}),v4h('div',{className:'v2-passage-wash','aria-hidden':true}),
  v4h('header',{className:'v4-friend-header'},v4h('div',{className:'v4-friend-title'},v4h('small',null,'마음 바다 탐험대'),v4h('h1',null,friend.name+'의 마음 섬')),v4h('nav',{'aria-label':'친구 섬 도구'},button('빛 표시',()=>{setMenu(!menu);setMapOpen(false);}),button('섬 지도',()=>{setMapOpen(!mapOpen);setMenu(false);}),button('설정',()=>setHelp(true)))),
  welcome&&!panel&&!menu&&!mapOpen&&v4h('aside',{className:'v4-friend-welcome'},v4h('strong',null,'천천히, 함께 산책해요'),v4h('p',null,state.length?'마음 식물에 다가가면 친구가 공개한 마음 말과 뜻을 볼 수 있어요.':'공개된 마음 식물은 아직 없어요. 섬은 자유롭게 산책할 수 있어요.'),v4h('div',null,state.length?button('마음 식물 밝히기',()=>guide('growth'),'primary'):button('산책 시작하기',()=>setWelcome(false),'primary'),button('접기',()=>setWelcome(false),'quiet'))),
  menu&&v4h('aside',{className:'v4-friend-menu','aria-label':'목적지 빛 표시'},v4h('strong',null,'어디를 살펴볼까요?'),state.length>0&&button('✧ 마음 식물',()=>guide('growth')),button('▤ 우리 반 게시판',()=>guide('board')),button('⚓ 돌아가는 부두',()=>guide('dock')),button('빛 표시 끄기',()=>{setLit(null);setMenu(false);setNotice('');},'quiet')),
  mapOpen&&v4h('aside',{className:'v4-friend-map','aria-label':'친구 섬 지도'},v4h('strong',null,friend.name+'의 섬'),v4h('svg',{viewBox:'0 0 140 118',role:'img','aria-label':'섬의 길과 연못, 현재 위치'},
    v4h('path',{d:Array.from({length:97},(_,i)=>{const a=i/96*Math.PI*2,x=Math.cos(a)*34,z=Math.sin(a)*29,r=.94/v2Radius(x,z);return(i?'L':'M')+(70+x*r*1.5).toFixed(1)+' '+(57+z*r*1.4).toFixed(1);}).join(' ')+' Z',fill:'#abc08e',stroke:'#e1d5b0',strokeWidth:5}),v4h('ellipse',{cx:87,cy:52,rx:9,ry:19,fill:'#97c7bd'}),v4h('path',{d:'M56 101 L59 75 L53 53 L78 45 L99 45 L107 70 M53 53 L42 42 L56 24 L78 20 L101 31 L99 45 M53 53 L30 59 L24 40',stroke:'#f7ead0',strokeWidth:3,fill:'none'}),v4h('circle',{cx:70+ui.x*1.5,cy:57+ui.z*1.4,r:4,fill:'#fff9e6',stroke:'#557e67',strokeWidth:2})),v4h('p',null,'길을 누르거나 방향키로 걸어가요.'),v4h('div',null,button('부두 밝히기',()=>{guide('dock');setMapOpen(false);}),button('접기',()=>setMapOpen(false),'quiet'))),
  ui.destination&&lit&&!panel&&!motion&&v4h('div',{className:'v4-friend-pin',style:{left:ui.destination.x+'%',top:ui.destination.y+'%'}},'✧ '+destinationTitle+(ui.destination.onScreen?'':' · 시점을 돌려 찾아보세요')),
  v4h('nav',{className:'v4-friend-controls','aria-label':'시점과 소리'},button('↶',()=>api.current?.rotate(-Math.PI/4),'','시점 왼쪽 회전'),button('↷',()=>api.current?.rotate(Math.PI/4),'','시점 오른쪽 회전'),button('−',()=>api.current?.zoom(2),'','축소'),button('+',()=>api.current?.zoom(-2),'','확대'),button('⌂',()=>api.current?.reset(),'','기본 시점'),v4h(SndBtn,{small:true})),
  v4h(V2Joystick,{paused:!!panel||help||!!motion,onMove:(x,z)=>api.current?.stick(x,z)}),
  v4h('p',{className:'v4-friend-hint'},'방향키 / WASD로 걷기 · 드래그로 둘러보기'),
  ui.nearest&&!panel&&!motion&&button('E / ㄷ  '+(ui.nearest.action==='sea'?'내 섬으로 · 배 타기':ui.nearest.action==='diary'?'내 안으로 · 친구의 개인 공간':ui.nearest.title+' · 열기'),()=>api.current?.interact(ui.nearest.action),'v4-friend-interact'),
  growth&&!ui.nearest&&!panel&&!motion&&v4h('section',{className:'v4-friend-growth','aria-label':'친구가 공개한 마음 말'},v4h('small',null,'친구가 공개한 마음'),v4h('h2',null,growth.label),v4h('p',null,emoMeaning(growth.label)||'기록에서 자란 마음 말'),v4h('button',{className:'primary',disabled:!socialReady||sending||rule!=='ready',onClick:send},sending?'마음을 보내는 중…':!socialReady?'마음 연결을 확인하고 있어요':rule==='sent'?'이 마음에는 오늘 이미 보냈어요':rule==='private'?'지금은 공개되지 않은 마음이에요':rule==='unfamiliar'?'같은 쪽 마음을 기록하면 보낼 수 있어요':'✧ 나도 그래')),
  notice&&!panel&&v4h('div',{className:'v4-friend-notice',role:'status'},v4h('span',null,notice),button('×',()=>setNotice(''),'quiet','안내 닫기')),
  failed&&v4h('div',{className:'v4-friend-failure',role:'alert'},v4h('p',null,failed),button('내 섬으로 돌아가기',()=>onOpen('sea'),'primary')),
  motion&&v4h('div',{className:'v2-passage-shield'},v4h('div',{className:'v2-passage-caption'},v4h('p',{role:'status'},motion.phase==='boarding'?'배에 올라요':motion.phase==='sailing'?'내 섬으로 돌아가요':'부두 끝으로 걸어가요'),button('바로 들어가기',()=>api.current?.skipPassage()),button('취소',()=>api.current?.cancelPassage()))),
  help&&v4h('div',{className:'v4-shade'},v4h('section',{className:'v4-dialog v4-friend-help',role:'dialog','aria-modal':true,'aria-label':'친구 섬 설정'},v4h('header',null,v4h('h2',null,'산책 도움말'),button('닫기',()=>setHelp(false))),v4h('p',null,'방향키 / WASD 또는 길을 눌러 걸어요. 드래그로 360도 둘러보고, 가까운 장소에서는 E / ㄷ을 눌러요.'),v4h('p',null,'작은 화면에서는 왼쪽 아래 조이스틱으로 걷고 화면을 밀어 둘러봐요.'),v4h('p',null,'친구가 공개한 마음 식물에는 마음 말과 뜻이 표시돼요. 친구의 개인 일기와 숨긴 마음은 열리지 않아요.'),v4h('h3',null,'화질'),v4h('div',{className:'v4-friend-quality'},['standard','low'].map(q=>v4h('button',{key:q,'aria-pressed':quality===q,onClick:()=>{V2_QUALITY=q;setQuality(q);}},q==='standard'?'표준 화질':'가벼운 화질'))),v4h('small',null,'가벼운 화질은 그림자와 해상도를 낮춰요.'))),
  V4_QUERY.get('inspect')==='1'&&v4h(V4FriendInspect,{api,host,onPose:setReviewPose,state}));
}
