/* V4 integration is loaded only by the verified memory preview. */
if(typeof __DB!=='object'||!document.querySelector('meta[http-equiv="Content-Security-Policy"]')?.content.includes("connect-src 'none'"))throw Error('V4 requires isolated memory preview');
V4State.configure({read:k=>__get('v4-local/'+k),write:async(k,v)=>{if(new URLSearchParams(location.search).get('saveFail')==='1')throw Error('local-write-failure');__set('v4-local/'+k,v);}});
const v4h=React.createElement,V4_SESSIONS={};
const V4_TABS=[['write','마음 쓰기','✎'],['review','마음 살펴보기','◉'],['talk','마음 대화','♡'],['practice','마음 연습','✧'],['archive','일기 모아보기','▤']];
function v4Analyze(raw){try{if(V4_QUERY.get('analysisFail')==='1')throw Error('local-analysis-failure');return analyzeEntry(raw);}catch{return{hits:[],excluded:[],matchedPos:[],matchedNeg:[],posScore:null,negScore:null,posPct:null,negPct:null,valence9:null,arousal9:null,valStd:null,aroStd:null,status:'unavailable'};}}
function V4App(props){
 const {me,entries,onAdd,onUpdate,onDelete,setEntries,onDiary,onLogout,onBoardSeen,onBoardClose}=props;
 const [view,setView]=useState(V4_QUERY.get('inspect')==='1'&&V4_QUERY.get('view')==='sea'?'sea':'world'),[friend,setFriend]=useState(null),[seaFrom,setSeaFrom]=useState(null),[panel,setPanel]=useState(props.initialPanel),[data,setData]=useState(()=>V4State.load(me)),[error,setError]=useState(''),[state,setState]=useState(()=>islandState(entries||[]));
 const [placeRequest,setPlaceRequest]=useState(null),[celebrate,setCelebrate]=useState(false);
 function leavePlace(id,message=''){setPanel(null);setPlaceRequest({id,message,token:Date.now()});requestAnimationFrame(()=>document.querySelector('.v2-canvas canvas')?.focus({preventScroll:true}));}
 function earned(){setCelebrate(!data.reward.available);setPanel('reward');}
 const alive=useRef(true);useEffect(()=>()=>{alive.current=false;},[]);
 useEffect(()=>{let active=true;v2LoadOwnIsland(me).then(s=>{if(active)setState(s);}).catch(()=>{});return()=>{active=false;};},[entries,me.id]);
 async function change(event){const next=await V4State.dispatch(me,event);if(alive.current)setData(next);return next;}
 async function addEntry(e){if(V4_QUERY.get('saveFail')==='1')throw Error('local-write-failure');await onAdd(e);}
 async function clearLinkedChat(ts){const chats=await sGet(chatKey(me.id));if(Array.isArray(chats))await dbRef(chatKey(me.id)).set(chats.filter(ch=>ch.entryTs!==ts));}
 async function updateEntry(e){await onUpdate(e);await clearLinkedChat(e.ts);setEntries(entries.map(x=>x.ts===e.ts?e:x));await change({type:'edit',ts:e.ts});}
 async function deleteEntry(e){await change({type:'forget',ts:e.ts});await clearLinkedChat(e.ts);await onDelete(e);setEntries(old=>old.filter(x=>x.ts!==e.ts));}
 function open(where){setError('');if(where==='sea'){setPanel(null);setSeaFrom(view==='friend'?{fromId:friend.id,autoHome:true}:null);setView('sea');}else if(where==='diary'||where==='private'){if(view==='friend')setPanel('private');else setPanel('write');}else setPanel(where);}
 function close(){setCelebrate(false);setPanel(null);onBoardClose?.();requestAnimationFrame(()=>document.querySelector('.v2-canvas canvas')?.focus({preventScroll:true}));}
 async function visit(info){setView('loading');try{const f=await v2LoadPublicIsland(me,info);setFriend(f);setView('friend');}catch(e){setError('친구 섬을 열지 못했어요. 다시 선택해 주세요.');setView('sea');}}
 if(view==='loading')return v4h('div',{className:'v2-loading',role:'status'},'친구의 마음 섬에 닿고 있어요…');
 if(view==='sea')return v4h('div',{className:'v2-legacy'},v4h(V4SeaView,{me,entries,reward:data.reward,arrive:seaFrom,tutOn:props.tutOn,onTour:props.onTour,onBack:()=>{setView('world');setSeaFrom(null);},onGo:(where,info)=>{if(where==='friend'&&info)visit(info);}}),error&&v4h('p',{role:'alert'},error));
 return v4h(React.Fragment,null,
  view==='friend'?v4h(V4FriendWorld,{key:friend.id,state:friend.state,myState:state,me,friend,panel,onOpen:open}):v4h(V4World,{me,data,change,panel,onOpen:open,onLogout,placeRequest}),
  V4_TABS.some(t=>t[0]===panel)&&v4h(V4Activities,{me,data,change,entries,panel,onLeavePlace:leavePlace,onEarned:earned,onClose:close,onAdd:addEntry,onUpdate:updateEntry,onDelete:deleteEntry,setEntries,onLegacy:onDiary}),
  panel==='reward'&&v4h(V4Rewards,{data,change,celebrate,onClose:close,onShow:()=>{setCelebrate(false);leavePlace('decoration','소품을 놓은 자리가 반짝여요. 가까이에서 살펴보세요.');}}),
  panel==='board'&&v4h(V2Board,{me,myState:state,onSeen:onBoardSeen,onBack:close}),
  panel==='private'&&v4h('div',{className:'v2-modal-shade'},v4h('section',{className:'v2-help',role:'dialog','aria-modal':true,'aria-label':'친구의 개인 공간'},v4h('h2',null,'친구만의 공간이에요'),v4h('p',null,'친구의 개인 일기는 공개되지 않아요.'),v4h('button',{onClick:close,autoFocus:true},'산책 계속하기'))));
}
function V4World({me,data,change,panel,onOpen,onLogout,placeRequest}){
 const host=useRef(null),api=useRef(null),openRef=useRef(onOpen);openRef.current=onOpen;
 const [ui,setUI]=useState({}),[quality,setQuality]=useState('standard'),[help,setHelp]=useState(false),[map,setMap]=useState(false),[motion,setMotion]=useState(null),[collapsed,setCollapsed]=useState(()=>innerWidth<700),[notice,setNotice]=useState(''),[failed,setFailed]=useState(''),[lit,setLit]=useState(null);
 useEffect(()=>{SND.loop('bgm');try{api.current=v4CreateWorld(host.current,[],{open:a=>openRef.current(a),update:setUI,motion:setMotion},V4_SESSIONS[me.id],{quality,islandId:me.id});window.__V4=api.current;api.current.setDecoration(data.reward);}catch(e){setFailed('섬 화면을 열지 못했어요. 마음 활동 바로가기를 이용해 주세요.');console.error(e);}return()=>{SND.leave();if(api.current){V4_SESSIONS[me.id]=api.current.snapshot();api.current.dispose();}delete window.__V4;};},[me.id,quality]);
 useEffect(()=>{api.current?.pause(!!panel||help);},[panel,help,quality]);useEffect(()=>{api.current?.setDecoration(data.reward);},[data.reward.item,data.reward.spot,quality]);
 async function act(event){try{await change(event);}catch(e){setNotice('저장하지 못했어요. 다시 눌러 주세요.');}}
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(timer);},[notice]);
 const q=data.q,destination=q.stage==='write'?'write':'review';
 const button=(text,fn,cls='',label)=>v4h('button',{type:'button',className:cls,onClick:fn,'aria-label':label},text);
 function guide(id,message){setLit(id);api.current?.setDestination(id);setNotice(message||((V4.stops[id]?.title||'소품')+' 자리가 빛나요. 직접 걸어가 보세요.'));setMap(false);}
 useEffect(()=>{if(q.active)guide(destination);else if(q.stage==='complete'){setLit(null);api.current?.setDestination(null);}},[q.active,q.stage]);
 useEffect(()=>{if(placeRequest)guide(placeRequest.id,placeRequest.message);},[placeRequest?.token]);
 useEffect(()=>{api.current?.setDestination(lit);},[quality,lit]);
 return v4h('main',{className:'v2-world v4-world','aria-hidden':panel?true:undefined,inert:panel?'':undefined},v4h('div',{className:'v2-canvas',ref:host,'data-testid':'v4-world'}),v4h('div',{className:'v2-vignette'}),v4h('div',{className:'v2-passage-wash'}),
  v4h('header',{className:'v4-brand'},v4h('span',{className:'v4-seal','aria-hidden':true},'⚓'),v4h('div',null,v4h('small',null,'마음 바다 탐험대'),v4h('h1',null,'내 마음섬'))),
  v4h('nav',{className:'v4-tools','aria-label':'섬 도구'},button('마음 활동',()=>setMap(!map)),button('꾸미기',()=>onOpen('reward')),button('설정',()=>setHelp(true))),
  v4h('section',{className:'v4-quest'+(collapsed?' is-collapsed':''),'aria-label':'오늘의 마음 탐험'},button('☀  오늘의 마음 탐험  '+(collapsed?'＋':'−'),()=>setCollapsed(!collapsed),'v4-quest-title'),!collapsed&&v4h(React.Fragment,null,v4h('h2',null,V4Content.title),v4h('p',null,q.stage==='complete'?'마음 말의 뜻과 차이를 살펴봤어요.':q.stage==='offer'?'작은 이야기에서 시작해 볼까요?':q.stage==='write'?'나무 아래 책상에서 이야기를 골라요.':q.stage==='feedback'?'남긴 생각과 피드백을 확인해요.':'관찰대에서 비슷한 마음 말을 비교해요.'),v4h('div',{className:'v4-progress'},['이야기','말 비교','꾸미기'].map((s,i)=>v4h('span',{key:s,className:((q.stage==='write'||q.stage==='offer')?i===0:q.stage==='complete'?i===2:i===1)?'current':''},s))),q.stage==='complete'?v4h('div',{className:'v4-actions'},button(data.reward.item?'내 소품 보기':'소품 선택하기',()=>onOpen('reward'),'v4-primary'),button('다시 연습',()=>act({type:'restart'}))):q.active?v4h(React.Fragment,null,v4h('div',{className:'v4-actions'},button('목적지 밝히기',()=>guide(destination),'v4-primary')),v4h('div',{className:'v4-actions'},button('빛 표시 끄기',()=>{setLit(null);api.current?.setDestination(null);},'v4-text'),button('다음에 하기',()=>act({type:'defer'}),'v4-text'))):button(q.stage==='offer'?'탐험 시작하기':'이어서 탐험하기',()=>act({type:'start'}),'v4-primary'))),
  map&&v4h('aside',{className:'v4-map'},v4h('h2',null,'어디로 갈까요?'),V4_TABS.map(([id,title,icon])=>v4h('div',{key:id},button(icon+' '+title,()=>guide(id),'',title+' 장소 밝히기'))),v4h('div',null,button('우리 반 게시판',()=>guide('board')),button('부두',()=>guide('dock')))),
  ui.pin&&!panel&&v4h('div',{className:'v4-beacon-label',style:{left:ui.pin.x+'%',top:ui.pin.y+'%'}},v4h('span',{'aria-hidden':true},'✦'),v4h('strong',null,ui.pin.title),v4h('small',null,ui.pin.id==='decoration'?'내 섬에 놓았어요':ui.pin.near?'가까이에 있어요 · 아래에서 열기':'빛나는 곳으로 걸어가요')),
  v4h('div',{className:'v4-bottom'},button('↶',()=>api.current?.rotate(-Math.PI/4),'','시점 왼쪽 회전'),button('↷',()=>api.current?.rotate(Math.PI/4),'','시점 오른쪽 회전'),button('−',()=>api.current?.zoom(2),'','축소'),button('+',()=>api.current?.zoom(-2),'','확대'),button('⌂',()=>api.current?.reset(),'','기본 시점'),v4h(SndBtn,{small:true})),
  v4h('p',{className:'v4-hint'},'WASD / 방향키 · 드래그로 둘러보기'),v4h(V2Joystick,{paused:!!panel||help||!!motion,onMove:(x,z)=>api.current?.stick(x,z)}),
  ui.nearest&&!panel&&!motion&&button('E / ㄷ  '+ui.nearest.title+(ui.nearest.action==='sea'?' · 배 타기':' · 열기'),()=>api.current?.interact(ui.nearest.action),'v4-interact'),
  notice&&!panel&&v4h('div',{className:'v4-notice',role:'status'},notice,button('×',()=>setNotice(''),'','안내 닫기')),
  failed&&v4h('div',{className:'v4-notice',role:'alert'},failed,V4_TABS.map(([id,title])=>button(title,()=>onOpen(id)))),
  motion&&v4h('div',{className:'v2-passage-shield'},v4h('div',{className:'v2-passage-caption'},v4h('p',{role:'status'},'배를 타고 친구들의 바다로 가요'),button('바로 들어가기',()=>api.current?.skipPassage()),button('취소',()=>api.current?.cancelPassage()))),
  help&&v4h(V4Dialog,{title:'편안하게 탐험하기',onClose:()=>setHelp(false)},v4h('p',null,'방향키 또는 WASD로 걸어요. 길을 눌러 걸을 수도 있어요. 화면을 드래그하면 360도로 둘러봐요.'),v4h('p',null,'장소 가까이에서 E 또는 ㄷ을 누르세요. 글을 쓸 때는 캐릭터가 움직이지 않아요.'),v4h('div',{className:'v4-actions'},button('표준 화질',()=>setQuality('standard')),button('가벼운 화질',()=>setQuality('low'))),v4h('p',{className:'v4-muted'},'로컬 검수용 섬 · 새로고침하면 연습 기록이 초기화돼요.'),button('처음으로',onLogout)),
  V4_QUERY.get('inspect')==='1'&&v4h(V4Inspect,{api,host,data}));
}
function V4Dialog({title,onClose,children,wide=false}){
 const ref=useRef(null);useEffect(()=>{const old=document.activeElement;ref.current?.querySelector('h2')?.focus();return()=>old?.isConnected&&old.focus?.();},[]);
 function keys(e){if(e.key==='Escape'&&!e.isComposing){e.stopPropagation();onClose();}if(e.key==='Tab'){const list=[...ref.current.querySelectorAll('button,input,textarea,select,a[href]')].filter(e=>!e.disabled&&e.getClientRects().length),first=list[0],last=list[list.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement.tagName==='H2')){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}
 return v4h('div',{className:'v4-shade',onKeyDown:keys},v4h('section',{className:'v4-dialog'+(wide?' v4-wide':''),ref,role:'dialog','aria-modal':true,'aria-label':title},v4h('header',null,v4h('h2',{tabIndex:-1},title),v4h('button',{onClick:onClose,'aria-label':'섬으로 돌아가기'},'섬으로 ×')),children));
}
function V4Activities({me,data,change,entries,panel,onLeavePlace,onEarned,onClose,onAdd,onUpdate,onDelete,setEntries,onLegacy}){
 const [text,setText]=useState(data.draft),[kind,setKind]=useState('personal'),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[choices,setChoices]=useState(data.q.response?.choices||[]),[thought,setThought]=useState(data.q.response?.thought||''),[help,setHelp]=useState(false),[correction,setCorrection]=useState(null),[edit,setEdit]=useState(null);
 const lock=useRef(false),pendingEntry=useRef(null);
 const q=data.q,context=data.context||q.source,sourceEntry=context?.kind==='personal'?entries.find(e=>e.ts===context.entryTs):null,selected=entries.find(e=>e.ts===data.selectedEntryTs)||entries[entries.length-1];
 const textSource=context?.kind==='fiction'?V4Content.story:sourceEntry?.text||selected?.text||'';
 async function run(fn){if(lock.current)return;lock.current=true;setBusy(true);setNotice('');try{await fn();}catch(e){setNotice('저장하지 못했어요. 입력은 그대로예요. 다시 시도해 주세요.');}finally{lock.current=false;setBusy(false);}}
 async function saveSource(quest){await run(async()=>{if(kind==='fiction'){await change({type:'source',source:{kind:'fiction',caseId:'Q01-case-1'}});}else{if(!text.trim())return;if(!pendingEntry.current||pendingEntry.current.text!==text){let ts=Date.now();while(entries.some(e=>e.ts===ts))ts++;pendingEntry.current={ts,date:todayStr(),text,analysis:v4Analyze(text)};}const entry=pendingEntry.current;await onAdd(entry);setEntries(old=>old.some(e=>e.ts===entry.ts)?old:[...old,entry]);if(quest)await change({type:'source',source:{kind:'personal',entryTs:entry.ts}});else{await change({type:'selectEntry',ts:entry.ts});await change({type:'draft',text:''});}pendingEntry.current=null;setText('');}setNotice('저장했어요.');onLeavePlace('review',kind==='fiction'?'이야기를 골랐어요. 빛나는 관찰대에서 마음을 살펴봐요.':'일기를 저장했어요. 마음을 살펴보고 싶다면 빛나는 관찰대로 가세요.');});}

 function toggle(label){setChoices(old=>old.includes(label)?old.filter(x=>x!==label):[...old,label]);}
 const b=(label,onClick,cls='',disabled=false)=>v4h('button',{type:'button',onClick,className:cls,disabled:busy||disabled},label);
 const hitEntry=sourceEntry||selected,hits=hitEntry?.analysis?.hits||[];
 const sourceBlock=v4h('section',{className:'v4-source'},v4h('small',null,context?.kind==='fiction'?'가상 이야기 · 연습용':'내 기록'),v4h('p',null,textSource||'이야기를 먼저 골라 주세요.'));
 return v4h(V4Dialog,{title:V4_TABS.find(t=>t[0]===panel)?.[1]||'마음 활동',onClose,wide:true},v4h('p',{className:'v4-place-caption'},({write:'내 안으로 · 나무 아래 책상에서 나의 이야기를 남겨요',review:'물가 관찰대 · 마음 말의 뜻과 차이를 살펴보는 곳',talk:'정원 벤치 · 마음에 남은 일을 이야기하는 곳',practice:'작은 작업대 · 천천히 연습하는 곳',archive:'기록 보관함 · 나의 일기를 다시 만나는 곳'})[panel]),v4h('div',{className:'v4-activity-body'},
  panel==='write'&&v4h(React.Fragment,null,v4h('div',{className:'v4-section-head'},v4h('small',null,q.active?'탐험 01 · 이야기에서 시작해요':'나만의 기록'),v4h('h3',null,'오늘 기억에 남는 순간이 있나요?'),v4h('p',null,'그때 어떤 마음이 들었나요? 특별한 일이 아니어도 좋아요.')),
   v4h('div',{className:'v4-actions'},b('내 경험 쓰기',()=>setKind('personal'),kind==='personal'?'v4-selected':''),b('가상 이야기로 탐험',()=>setKind('fiction'),kind==='fiction'?'v4-selected':'')),
   kind==='personal'?v4h(React.Fragment,null,v4h('label',{className:'v4-label',htmlFor:'v4-diary'},'내 이야기'),v4h('textarea',{id:'v4-diary',value:text,onChange:e=>{setText(e.target.value);change({type:'draft',text:e.target.value}).catch(()=>setNotice('임시 글을 보관하지 못했어요.'));},placeholder:'적고 싶은 만큼, 나의 말로 남겨 주세요.',rows:5}),b(help?'마음 말 도움 접기':'마음 말·상황 도움',()=>setHelp(!help),'v4-text'),help&&v4h('div',{className:'v4-help-copy'},v4h('p',null,'언제, 누구와, 어떤 일이 있었나요? 말이 떠오르지 않아도 그대로 남길 수 있어요.'),v4h('p',null,'편안 · 뿌듯 · 슬픔 · 짜증 · 불안 … 여러 마음이 함께 있어도 괜찮아요.'))):v4h('div',{className:'v4-story'},v4h('small',null,'가상 이야기 · 개인 일기로 저장하지 않아요'),v4h('p',null,V4Content.story)),
   v4h('div',{className:'v4-actions'},b(busy?'저장 중…':kind==='fiction'?'이 이야기로 시작하기':'일기 저장하기',()=>saveSource(kind==='fiction'||q.active),'v4-primary',kind==='personal'&&!text.trim()),b('나중에 이어쓰기',onClose)),
   entries.length>0&&v4h('details',null,v4h('summary',null,'지난 기록으로 시작하기'),entries.slice(-4).map(e=>v4h('button',{key:e.ts,className:'v4-record',onClick:()=>run(async()=>{await change({type:'source',source:{kind:'personal',entryTs:e.ts}});onLeavePlace('review','이야기를 골랐어요. 빛나는 관찰대로 가세요.');})},e.date+' · '+e.text.slice(0,65))))),
  panel==='review'&&v4h(React.Fragment,null,v4h('div',{className:'v4-section-head'},v4h('small',null,'마음 살펴보기'),v4h('h3',null,'나에게 가까운 말은 무엇일까요?'),v4h('p',null,'여러 마음이 함께 있어도, 아직 잘 모르겠어도 괜찮아요.')),sourceBlock,
   context?.kind!=='fiction'&&hitEntry&&v4h('section',{className:'v4-analysis'},v4h('h4',null,'내 글에서 찾은 마음 말'),v4h('small',null,hitEntry.analysis?.status==='unavailable'?'분석을 마치지 못했어요 · 원문은 저장됐어요':'자동으로 찾았어요 · 확정된 답은 아니에요'),hits.length?hits.map((h,i)=>{const raw=[h.token,...(EMOTIONS_28.find(e=>e.label===h.label)?.kw||[])].find(t=>t&&t!=='직접선택'&&hitEntry.text.includes(t));return v4h('div',{key:i},v4h('strong',null,h.label),v4h('p',null,emoMeaning(h.label)||'내가 직접 고른 마음 말이에요.'),raw&&v4h('p',null,'실제 표현: ',v4h('mark',null,raw)));}):v4h('p',null,hitEntry.analysis?.status==='unavailable'?'분석 상태와 관계없이 마음 말을 직접 고를 수 있어요.':'자동으로 찾은 마음 말이 없어요. 글은 그대로 저장됐어요.'),data.choices[String(hitEntry.ts)]?.length>0&&v4h('p',null,'내가 고른 말: '+data.choices[String(hitEntry.ts)].join(', ')),b('내 감정은 달라요',()=>setCorrection(correction?null:(data.choices[String(hitEntry.ts)]||[])),'v4-text'),correction&&v4h('div',null,v4h('div',{className:'v4-chips'},EMOTIONS_28.map(e=>v4h('button',{key:e.name,'aria-pressed':correction.includes(e.label),onClick:()=>setCorrection(v=>v.includes(e.label)?v.filter(x=>x!==e.label):[...v,e.label])},e.label))),b('내가 고른 마음 저장',()=>run(async()=>{await change({type:'choices',ts:hitEntry.ts,labels:correction});setCorrection(null);setNotice('원문과 자동 분석은 그대로 두고, 내가 고른 마음을 따로 저장했어요.');}),'v4-primary'))),
   v4h('div',{className:'v4-word-grid'},V4Content.words.map(w=>v4h('article',{key:w.label},v4h('h4',null,w.label),v4h('p',null,w.meaning),v4h('small',null,w.example)))),
   v4h('p',{className:'v4-callout'},'짜증·화남·분노를 고정된 단계로 줄 세우지 않아요. 뜻이 겹칠 수 있고 상황에 따라 달라져요.'),
   q.source&&JSON.stringify(context)===JSON.stringify(q.source)&&v4h('section',{className:'v4-response'},v4h('h4',null,'뜻을 비교해 보고, 가까운 표현을 골라요'),v4h('div',{className:'v4-chips'},['짜증','화남','분노','원래 표현','아직 어려워요'].map(label=>v4h('button',{key:label,'aria-pressed':choices.includes(label),onClick:()=>toggle(label)},label))),v4h('label',{className:'v4-label',htmlFor:'v4-thought'},'그렇게 고른 이유나 새롭게 생각한 점 (선택)'),v4h('textarea',{id:'v4-thought',value:thought,onChange:e=>setThought(e.target.value),rows:2}),choices.includes('아직 어려워요')&&v4h('p',{className:'v4-callout'},V4Content.unsure),b('생각 저장하고 피드백 보기',()=>run(()=>change({type:'response',choices,thought})),'v4-primary',!choices.length)),
   q.stage==='feedback'&&JSON.stringify(context)===JSON.stringify(q.source)&&v4h('section',{className:'v4-feedback',role:'status'},v4h('h4',null,'내가 남긴 선택을 돌아봐요'),v4h('p',null,'내 선택: '+q.response.choices.join(', ')),v4h('p',null,V4Content.feedback),b('피드백을 확인했어요 · 탐험 마치기',()=>run(async()=>{await change({type:'feedback'});onEarned();}),'v4-primary')),
   (!q.source||JSON.stringify(context)!==JSON.stringify(q.source))&&v4h('div',{className:'v4-actions'},b('책상에서 이야기 고르기',()=>onLeavePlace('write','빛나는 책상에서 이야기를 골라 주세요.'),'v4-primary')),
   v4h('details',{className:'v4-compass'},v4h('summary',null,'마음 나침반 살펴보기'),v4h(CircumplexChart,{entries:context?.kind==='fiction'?[]:hitEntry?[hitEntry]:entries,hovIdx:null,onHover:()=>{},teacher:false}),v4h('p',null,'위: 에너지 높음 / 아래: 에너지 낮음'),v4h('p',null,'왼쪽: 부정 / 오른쪽: 긍정'),v4h('p',null,'좋고 나쁜 감정을 가르는 점수표가 아니에요. 풍경의 위치나 보상과 연결되지 않아요.'))),
  panel==='talk'&&v4h(React.Fragment,null,v4h('h3',null,'마음에 남는 일이 있나요?'),sourceBlock,context?.kind==='fiction'?v4h('p',null,'이 인물에게 어떤 도움이 필요할지 생각해 보세요. 내 경험을 공개하지 않아도 괜찮아요.'):v4h(MindChat,{allowAll:true,entries:sourceEntry?[sourceEntry]:selected?[selected]:entries,userId:me.id}),context?.kind==='fiction'&&v4h('label',null,'필요한 도움이나 해 볼 행동',v4h('textarea',{value:data.talk.fiction||'',onChange:e=>change({type:'talk',ts:null,text:e.target.value}).catch(()=>setNotice('생각을 보관하지 못했어요.')),rows:4}))),
  panel==='practice'&&v4h(React.Fragment,null,v4h('h3',null,'뜻과 차이를 천천히 연습해요'),v4h('p',null,'게임 점수나 속도는 마음을 이해하는 능력의 점수가 아니에요.'),v4h(GameHub,null)),
  panel==='archive'&&v4h(React.Fragment,null,v4h('h3',null,'나의 글과 배움을 다시 만나요'),v4h('p',null,'내 일기 '+entries.length+'편 · 가상 이야기 탐험은 포함하지 않아요.'),v4h('details',null,v4h('summary',null,'달력으로 보기'),v4h('div',{className:'v4-legacy'},v4h(DiaryView,{entries,setEntries,onAdd,onUpdate,onDelete,readOnly:false,userId:me.id,initialTab:'detail'}))),entries.slice().reverse().map(e=>v4h('article',{className:'v4-record-card',key:e.ts},v4h('small',null,e.date),edit===e.ts?v4h('textarea',{defaultValue:e.text,'aria-label':'기록 수정',id:'v4-edit-text'}):v4h('p',null,e.text),v4h('div',{className:'v4-actions'},b('이 글을 고르고 관찰대 밝히기',()=>run(async()=>{await change({type:'source',source:{kind:'personal',entryTs:e.ts}});onLeavePlace('review','이야기를 골랐어요. 빛나는 관찰대로 가세요.');})),edit===e.ts?b('수정 저장',()=>run(async()=>{const raw=document.getElementById('v4-edit-text').value;if(!raw.trim())return;await onUpdate({...e,text:raw,analysis:v4Analyze(raw)});setEdit(null);})):b('원문 수정',()=>setEdit(e.ts)),b('삭제',()=>run(()=>onDelete(e)))))),b('기존 일기·리포트 화면',onLegacy,'v4-text')),
  notice&&v4h('p',{className:'v4-save-notice',role:'status'},notice),busy&&v4h('p',{role:'status'},'저장 중이에요…')));
}
function V4GiftPreview({item,celebrate=false}){
 const host=useRef(null);
 useEffect(()=>{const T=THREE,node=host.current;let raf,renderer;try{
  const scene=new T.Scene(),camera=new T.PerspectiveCamera(34,1,.1,20);camera.position.set(1.35,1.35,2.3);camera.lookAt(0,.48,0);
  renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputEncoding=T.sRGBEncoding;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.9;
  scene.add(new T.HemisphereLight('#fff5df','#8ca7a0',1.1));const light=new T.DirectionalLight('#fff2d4',1.6);light.position.set(-3,6,5);scene.add(light);
  const gift=v4BuildReward(T,item);scene.add(gift);node.appendChild(renderer.domElement);
  const resize=()=>{const w=node.clientWidth,h=node.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();renderer.render(scene,camera);},observer=new ResizeObserver(resize);observer.observe(node);resize();
  const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,start=performance.now();function tick(now){const t=(now-start)/1000,u=Math.min(1,t/.7);gift.rotation.y=reduced?-.3:Math.sin(Math.min(t,8)*.65)*.35-.3;gift.position.y=reduced?0:Math.sin(Math.min(t,8)*1.5)*.025;gift.scale.setScalar(celebrate&&!reduced?1-Math.pow(1-u,3)+Math.sin(u*Math.PI)*.12:1);renderer.render(scene,camera);if(t<8&&!reduced)raf=requestAnimationFrame(tick);}tick(start);
  return()=>{cancelAnimationFrame(raf);observer.disconnect();v4DisposeReward(gift);renderer.dispose();renderer.domElement.remove();};
 }catch{renderer?.dispose();}},[item,celebrate]);
 return v4h('div',{className:'v4-gift-preview',ref:host,role:'img','aria-label':V4Content.items[item].name+' 소품 미리보기'},v4h('span',{className:'v4-gift-fallback'},V4Content.items[item].icon));
}
function V4Rewards({data,change,onClose,onShow,celebrate=false}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[acquired,setAcquired]=useState(false),lock=useRef(false);
 async function act(e){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await change(e);if(e.type==='choose')setAcquired(true);}catch{setError('선택을 저장하지 못했어요. 다시 눌러 주세요.');}finally{lock.current=false;setBusy(false);}}
 const r=data.reward,festive=celebrate||acquired;
 return v4h(V4Dialog,{title:r.available?(r.item?'나의 꾸미기 소품':'탐험을 마쳤어요!'):'나의 꾸미기',onClose},!r.available?v4h('p',null,'기본 풍경은 언제나 그대로예요. 마음 말 탐험을 마치면 작은 소품 하나를 더 고를 수 있어요.'):v4h(React.Fragment,null,
  v4h('section',{className:'v4-reward-celebration'+(festive?' is-new':''),'aria-label':'소품 획득 안내'},festive&&v4h('div',{className:'v4-confetti','aria-hidden':true},Array.from({length:12},(_,i)=>v4h('i',{key:i,style:{'--i':i,'--x':(i*37%100)+'%','--delay':i*.055+'s'}}))),v4h('small',null,r.item?'내가 얻은 작은 선물':'마음 탐험 01'),r.item?v4h(V4GiftPreview,{item:r.item,celebrate:acquired}):v4h('div',{className:'v4-gift-emblem','aria-hidden':true},'✦'),v4h('h3',{role:festive?'status':undefined},acquired?V4Content.items[r.item].name+'을 얻었어요!':r.item?V4Content.items[r.item].name:'마음을 살펴본 나에게, 작은 선물'),v4h('p',null,r.item?'이 소품은 내 것이 되었어요. 마음에 드는 자리에 놓아 보세요.':'소품 하나를 골라 나의 섬에 놓을 수 있어요.')),
  !r.item?v4h(React.Fragment,null,v4h('p',{className:'v4-muted'},'어떤 마음을 골랐든 같은 선택권이에요. 선택은 한 번만 해요.'),v4h('div',{className:'v4-reward-grid'},Object.entries(V4Content.items).map(([id,item])=>v4h('button',{key:id,disabled:busy,onClick:()=>act({type:'choose',item:id})},v4h('span',null,item.icon),v4h('strong',null,item.name),v4h('small',null,item.desc))))):v4h(React.Fragment,null,v4h('h3',null,'어디에 놓을까요?'),v4h('div',{className:'v4-placement-list'},Object.entries(V4Content.spots).map(([id,spot])=>v4h('button',{key:id,disabled:busy,'aria-pressed':r.spot===id,onClick:()=>act({type:'place',spot:id})},spot.name+(r.spot===id?' ✓':'')))),v4h('div',{className:'v4-actions'},v4h('button',{disabled:busy,onClick:()=>act({type:'place',spot:null})},'보관하기'),v4h('button',{className:'v4-primary',disabled:busy,onClick:r.spot?onShow:onClose},r.spot?'섬에 놓인 모습 보기':'소품함에 보관하고 닫기')),v4h('p',{role:'status'},r.spot?V4Content.spots[r.spot].name+'에 놓았어요.':'소품함에 보관 중이에요.'))),error&&v4h('p',{role:'alert'},error));
}
