/* Construct actual Three.js miniatures without a browser/renderer. Not a performance test. */
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const out='renders/releases/friend-sea-upgrade-20260920/',m=JSON.parse(fs.readFileSync(out+'manifest.json')),page=fs.readFileSync(out+'candidate/index.html','utf8');
const three=[...page.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(x=>x[1]).find(s=>s.includes('WebGLRenderer')&&s.includes('t.REVISION=e'));
const ctx=vm.createContext({console,URLSearchParams,location:{search:''},V4Content:{spots:{}},hashSeed:s=>[...String(s)].reduce((a,c)=>(a*31+c.charCodeAt(0))>>>0,0),mulberry32:n=>()=>{n=(n*1664525+1013904223)>>>0;return n/4294967296;}});vm.runInContext(three,ctx);for(const f of ['scene.js','sea-scene.js'])vm.runInContext(fs.readFileSync('prototypes/island-world-v2/v4/'+f,'utf8'),ctx);
const result=vm.runInContext(`(()=>{const all=[];for(let i=0;i<25;i++){const g=v4SeaFriendIsland('fake-'+i,{detail:.5});let meshes=0,triangles=0;g.traverse(o=>{if(o.isMesh){if(o.material.vertexColors&&!o.geometry.attributes.color)throw Error("Missing vertex colors");meshes++;triangles+=(o.geometry.index?.count||o.geometry.attributes.position.count)/3*(o.isInstancedMesh?o.count:1);for(const a of o.geometry.attributes.position.array)if(!Number.isFinite(a))throw Error('Nonfinite geometry');}});if(!g.userData.boat||!g.userData.v4NewIsland)throw Error('No boat');all.push({meshes,triangles});}const visible=v4SeaLearningPlants([{label:'기쁨',q:'HA'},{label:'숨긴말',q:'LA',hidden:true}],'fake');const blank=v4SeaLearningPlants([],'fake');return{islands:all.length,meshes:all[0].meshes,triangles:all[0].triangles,visiblePlants:visible.children.reduce((a,o)=>a+o.count,0),blankPlants:blank.children.length};})()`,ctx);
assert.equal(result.islands,25);assert.equal(result.visiblePlants,2);assert.equal(result.blankPlants,0);assert(result.meshes<60);
// Render the changed React components into trees using hook stubs to catch missing identifiers and changed UI paths.
const ui=vm.createContext({console,URL,URLSearchParams,document:{currentScript:{src:'http://localhost/app.js'}},location:{search:''},innerWidth:1280,V2_QUALITY:'standard',V4_QUERY:new URLSearchParams(),React:{createElement:(type,props,...children)=>({type,props,children}),Fragment:'fragment'},useState:x=>[typeof x==='function'?x():x,()=>{}],useRef:x=>({current:x}),useEffect(){},V2Joystick(){},V4Dialog(){},SND:{playing:()=>false},dayStamp:()=> '2026-09-20',V4FriendInspect(){}});
vm.runInContext('const v4h=React.createElement;const V4_UI_ASSETS=new URL("http://localhost/");function v4ToolIcon(n){return {icon:n};}function V4SoundButton(){}',ui);vm.runInContext(fs.readFileSync('prototypes/island-world-v2/v4/friend-view.js','utf8'),ui);const tree=vm.runInContext('V4FriendWorld({me:{id:"a"},friend:{id:"b",name:"가상 친구"},state:[],myState:[],onOpen(){},panel:null})',ui);assert(JSON.stringify(tree).includes('공개 일기'));assert(!JSON.stringify(tree).includes('WASD'));
console.log(JSON.stringify({pass:true,...result,checks:['25 actual Three.js miniatures constructed','finite terrain vertices and correct boat navigation metadata','only public emotion plants; empty private growth stays empty','friend component renders with public diary entry','not browser or real-device performance verification']}));
